name:                morsr
version:             0.1.0.0
github:              "brunolange/morsr"
license:             BSD3
author:              "Bruno Lange"
maintainer:          "blangeram@gmail.com"
copyright:           "2019 Bruno Lange"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brunolange/morsr#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  morsr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morsr

tests:
  morsr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morsr
